---
- name: Install Kubeflow master
  hosts: master
  become: yes
  tasks:
    - name: Create master folder
      ansible.builtin.file:
        path: /home/<master_username>/master
        state: directory
    - name: Copy Kubeflow Installation script
      ansible.builtin.copy:
        src: ../master/kubeflow-install.sh
        dest: /home/<master_username>/master/kubeflow-install.sh
        mode: 0755  # Ensure script has execute permissions
    - name: Execute Installation Script
      shell: /home/<master_username>/master/kubeflow-install.sh
