apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-registry
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: dataset-registry
        imagePullPolicy: Always
        image: gkorod/dataset-registry:v1.0
        ports:
        - containerPort: 4422
          name: http
        volumeMounts:
        - mountPath: "/datasets"
          name: data-volume
        env:
        - name: ENV_PATH
          value: "/datasets"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: datasets
