apiVersion: v1
kind: Pod
metadata:
  name: topo-pod
  namespace: kubeflow
  labels:
    app: topo
spec:
  restartPolicy: OnFailure  # Options: Always, OnFailure, Never
  containers:
  - name: topo
    image: gkorod/topo:v1.1
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1  # Limiting to 1 GPU
    volumeMounts:
    - mountPath: "/trained_models"
      name: data-volume
    - mountPath: "/datasets"
      name: data-volume2
  volumes:
  - name: data-volume2
    persistentVolumeClaim:
      claimName: datasets
  - name: data-volume
    persistentVolumeClaim:
      claimName: trained-models
  runtimeClassName: nvidia  # Specify the runtime class for NVIDIA GPUs
