name: Run EPOS Kubeflow Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kfp==2.0.3 requests pyyaml kfp-kubernetes==1.8.4

      - name: Run pipeline script
        env:
          INITIALIZER_IP: ${{ secrets.INITIALIZER_IP }}
          INITIALIZER_PORT: ${{ secrets.INITIALIZER_PORT }}
        run: |
          export INITIALIZER_IP=${{ secrets.INITIALIZER_IP }}
          export INITIALIZER_PORT=${{ secrets.INITIALIZER_PORT }}
          python pipeline_dsl_example/topo_example.py \
            --initializer-ip "$INITIALIZER_IP" \
            --initializer-port "$INITIALIZER_PORT"

